spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: ${DB-NAME}
        instance-connection-name: ${DB-INSTANCE}
      logging:
        enabled: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP-USERNAME}
    password: ${SMTP-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  url: ${API-URL}