spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: ${DB-NAME}
        instance-connection-name: ${DB-INSTANCE}
      logging:
        enabled: true
  sql:
    init:
      mode: always
api:
  url: ${API-URL}